// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0
// source: employee.sql

package postgres

import (
	"context"
	"database/sql"
)

const getAllEmployee = `-- name: GetAllEmployee :many
SELECT employee_id, "name", company_name, email, address
FROM public.employee
`

func (q *Queries) GetAllEmployee(ctx context.Context) ([]Employee, error) {
	rows, err := q.db.QueryContext(ctx, getAllEmployee)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Employee
	for rows.Next() {
		var i Employee
		if err := rows.Scan(
			&i.EmployeeID,
			&i.Name,
			&i.CompanyName,
			&i.Email,
			&i.Address,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEmployeeById = `-- name: GetEmployeeById :one
SELECT employee_id, "name", company_name, email, address
FROM public.employee
where employee_id = $1
`

func (q *Queries) GetEmployeeById(ctx context.Context, employeeID string) (Employee, error) {
	row := q.db.QueryRowContext(ctx, getEmployeeById, employeeID)
	var i Employee
	err := row.Scan(
		&i.EmployeeID,
		&i.Name,
		&i.CompanyName,
		&i.Email,
		&i.Address,
	)
	return i, err
}

const insertEmployee = `-- name: InsertEmployee :exec
INSERT INTO public.employee
    (employee_id, "name", company_name, email, address)
VALUES ($1, $2, $3, $4, $5)
`

type InsertEmployeeParams struct {
	EmployeeID  string         `json:"employee_id"`
	Name        sql.NullString `json:"name"`
	CompanyName string         `json:"company_name"`
	Email       sql.NullString `json:"email"`
	Address     sql.NullString `json:"address"`
}

func (q *Queries) InsertEmployee(ctx context.Context, arg InsertEmployeeParams) error {
	_, err := q.db.ExecContext(ctx, insertEmployee,
		arg.EmployeeID,
		arg.Name,
		arg.CompanyName,
		arg.Email,
		arg.Address,
	)
	return err
}

const updateDataEmployee = `-- name: UpdateDataEmployee :exec
UPDATE public.employee
SET "name"= $2,
    company_name= $3,
    email= $4,
    address= $5
WHERE employee_id = $1
`

type UpdateDataEmployeeParams struct {
	EmployeeID  string         `json:"employee_id"`
	Name        sql.NullString `json:"name"`
	CompanyName string         `json:"company_name"`
	Email       sql.NullString `json:"email"`
	Address     sql.NullString `json:"address"`
}

func (q *Queries) UpdateDataEmployee(ctx context.Context, arg UpdateDataEmployeeParams) error {
	_, err := q.db.ExecContext(ctx, updateDataEmployee,
		arg.EmployeeID,
		arg.Name,
		arg.CompanyName,
		arg.Email,
		arg.Address,
	)
	return err
}
