// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0

package postgres

import (
	"database/sql"
)

type Employee struct {
	EmployeeID  string         `json:"employee_id"`
	Name        sql.NullString `json:"name"`
	CompanyName string         `json:"company_name"`
	Email       sql.NullString `json:"email"`
	Address     sql.NullString `json:"address"`
}
