package models

// IncomingScanRequest is the payload sent by warehouse Action UI when scanning
// incoming raw material packing list / kanban.
//
// The QR/barcode on physical packing list encodes packing_number + item_uniq_code.
// The backend will resolve delivery_note_items internally — caller does NOT need
// to know the internal bigint IDs.
//
// Note: inventory is NOT updated here; it will be updated only after QC approval.
type IncomingScanRequest struct {
	// PackingNumber is scanned from QR/barcode on physical packing list (e.g. "KB-123456").
	// Used to lookup delivery_note_items.
	PackingNumber string `json:"packing_number" binding:"required"`

	// ItemUniqCode is the material unique code (e.g. "UQ-123456").
	// Shown on kanban/packing label. Used together with PackingNumber for lookup.
	ItemUniqCode string `json:"item_uniq_code" binding:"required"`

	// ClientEventID is the idempotency key generated by the client per scan.
	// Generate a UUID per scan event to prevent duplicate submissions on retry.
	ClientEventID string `json:"client_event_id" binding:"required,uuid"`

	DeltaQty int    `json:"delta_qty" binding:"required"`
	UOM      string `json:"uom" binding:"required"`

	// DeltaWeightKg is optional; used for weight-tracked items (e.g. wire/sheet).
	DeltaWeightKg *float64 `json:"delta_weight"`
}

// IncomingLookupRequest resolves packing_number → DN context for UI auto-fill.
// Call this when QR is scanned to populate form fields before submit.
type IncomingLookupRequest struct {
	PackingNumber string `json:"packing_number" form:"packing_number" binding:"required"`
	ItemUniqCode  string `json:"item_uniq_code" form:"item_uniq_code"`
}
