package models

// IncomingScanRequest is the payload sent by warehouse Action UI when scanning
// incoming raw material packing list / kanban.
//
// Note: inventory is NOT updated here; it will be updated only after QC approval.
type IncomingScanRequest struct {
	// DNID is incoming_dns.id (uuid).
	DNID string `json:"dn_id" binding:"required"`

	// DNItemID is incoming_dn_items.id (uuid).
	DNItemID string `json:"dn_item_id" binding:"required"`

	// ClientEventID is the idempotency key generated by the client per scan.
	ClientEventID string `json:"client_event_id" binding:"required"`

	PackingNumber string `json:"packing_number"`
	ItemUniqCode  string `json:"item_uniq_code" binding:"required"`

	DeltaQty int    `json:"delta_qty" binding:"required"`
	UOM      string `json:"uom" binding:"required"`

	// DeltaWeightKg is optional; used for weight-tracked items (e.g. wire).
	DeltaWeightKg *float64 `json:"delta_weight"`
}
